Additional improvements + customizations for RG
MetaFam/skill-bot pull request #7
Opened 2021-12-09 08:26 UTC by Flip-Liquid

- Added instructions for system dependencies (graphviz)
- Added support for using custom emojis with new skills
- Fixed issue where font was not being applied on graphs
- Added run local steps
- Added additional RG customization for copy/messages in the bot
- Added aesthetic customization for RG (custom fonts, coloring)

2021-12-12 23:02 UTC, mprimi requested changes
@Flip-Liquid thank you very much for submitting this changes.

The code here needs a few changes before it's ready for merge.

Maybe let's set up a time to meet on a video call and hammer everything out?

Before we meet, would you be able to rewrite history so commits are atomic (each commit doing exactly one thing). Right now you make changes in the first commit and then fix it in a commit later. So I have to look at the entire PR to see the final code. But the PR does a number of things, so it's overall hard to review and discuss.

If you are a git ninja, this should take just a few minutes. But if you've not done this before it can be quite intimidating, confusing and error prone. In that case let's do it together.

2021-12-12 23:02 UTC, mprimi commented on bot/commands.py
> +        if skill_emoji not in emoji.UNICODE_EMOJI['en']:
This is a cute idea, but I'm afraid it makes it harder for people to understand how to use it.
Also this logic here becomes quite dense (earlier it was just "replace whitespace with underscores" now there's a bunch of edge cases

2021-12-12 23:02 UTC, mprimi commented on bot/commands.py
> +            raise Exception()
This needs an error message

2021-12-12 23:02 UTC, mprimi commented on bot/messages.py
> +WORD_CLOUD_MESSAGE = "Word size is proportional to number of raiders..."
These 2 seem RG-specific messages

2021-12-12 23:02 UTC, mprimi commented on bot/messages.py
> +WORD_CLOUD_MESSAGE = "Word size is proportional to number of raiders..."
And I see a few more below.

The bot is deployed on servers where people use it for 'interests' and they don't know what a 'raider' is, so we would need to accommodate.

2021-12-12 23:02 UTC, mprimi commented on bot/commands.py
> +            raise Exception(f'{k.DRAW_SKILLS_ERROR_MESSAGE}. No {k.ENTITY_SHORT} supplied!')
I don't think `DRAW_SKILLS_ERROR_MESSAGE` belongs here, at least with its current value

2021-12-12 23:02 UTC, mprimi commented on repository/core.py
> +            skill_emoji TEXT NOT NULL
Modifying the database schema means the bot is not backward compatible, so we can't upgrade existing instances. This would be a reason to separate out this change into a separate PR for just future deployments.

2021-12-12 23:02 UTC, mprimi commented on repository/core.py
> +            skill_emoji TEXT NOT NULL
Or I suppose adding a default could work. Not sure, would need to be tested.

2021-12-12 23:02 UTC, mprimi commented on repository/core.py
> +        try:
This is hacky. And if you really wanted to go this way, this would be a good spot to set default emoji for rows that don't have one.

2021-12-12 23:02 UTC, mprimi commented on repository/core.py
> +            model.Skill(sid, sname, semoji)
Use of undeclared variable?

2021-12-12 23:02 UTC, mprimi commented on requirements.system
> +graphviz
I don't think graphviz is a system level requirement. The python package bundles it.
Virtualenv is also not strictly necessary.
So the only valid one here is Python 3.9, which is such a 'root' dependency that I don't think belongs in this file.

2021-12-13 00:12 UTC, Flip-Liquid commented on requirements.system
> +graphviz
graphviz was a system level requirement when I tried first running the graphing apis. it required an apt install to resolve the error that was returned. We can remove the virtualenv, but I think graphviz should probably be kept.

2021-12-13 00:14 UTC, Flip-Liquid commented on repository/core.py
> +        try:
yep! quite hacky. but it also only runs once. regardless, open to suggestions. seemed like a quick and dirty way to make sure that we could port existing data to the new schema.

2021-12-13 00:15 UTC, Flip-Liquid commented on repository/core.py
> +            skill_emoji TEXT NOT NULL
line 63+ addresses backcompat. agree that a configurable default could be added also.

2021-12-13 00:16 UTC, Flip-Liquid commented on bot/messages.py
> +WORD_CLOUD_MESSAGE = "Word size is proportional to number of raiders..."
Yep, a lot of these will need to be extracted into Strings for applying customization.

2021-12-13 05:07 UTC, Flip-Liquid commented on repository/core.py
> +            model.Skill(sid, sname, semoji)
this was extending line 154

2021-12-17 01:21 UTC, Flip-Liquid commented
going to close the PR + re-structure the commit history as suggested by @mprimi

2021-12-17 01:21 UTC, closed without merging